#!/usr/bin/bash
# Build all of the programs

# Show executed commands
set -xe

# Build the CGovnOS virtual machine
./build

# Build the GovnOS operating system
  # Debug modes:
  #   -D: show compilation success
  #   -F: show everyting
./gasmbb GOVNOS/BOOT.ASM GOVNOS/BOOT.B $1

# Build mkfs.govnfs
cd src/mkfs.govnfs/
./build
cd ../../

# Build gboot
cd src/gboot/
./build
cd ../../

# Build GASMAN
cd src/gasman/
./build
cd ../../

