#!/usr/bin/bash
# Build GovnOS

# Show executed commands
set -xe

# Build the GovnOS oeprating system
  # Debug modes:
  #   -D: show compilation success
  #   -F: show everyting
./gasmbb GOVNOS/BOOT.ASM GOVNOS/BOOT.B $1

